### ISSUE TITLE
Nono Live Electronics Overview

### ISSUE THREAD

**Issue by grammaton** [s-e-a-m/faust-libraries#10]
Una tabella in cui sono intavolati gli organici delle opere di Nono con live electronics.

**Comment by DavideTedesco** [comment]
Dovrebbero essere questi i brani:

[NL_Live_Electronics.txt](https://github.com/s-e-a-m/faust-libraries/files/4570931/NL_Live_Electronics.txt)

**Comment by grammaton** [comment]
Data | Titolo | Ensemble | Ensemble | Live Electronics | Live Electronics | Live Electronics 
-----|-------|-----------|-----------|-----------------|-----------------|-----------------
1979 | Con Luigi Dallapiccola | Percussioni |  - | Ring Modulators | Oscillators
1981 | Das atmende Klarsein | Flauto | Coro | Halafon | Delay | Harmonizer
1981 | Io, frammento dal Prometeo
1982 | Quando stanno morendo. Diario polacco n. 2
1983 | Guai ai gelidi mostri
1983 | Omaggio a György Kurtág
1984 | Prometeo. Tragedia dell’ascolto
1985 | A Pierre. Dell’azzurro silenzio, inquietum
1986 | Risonanze erranti. Liederzyklus a Massimo Cacciari
1987 | 1° Caminantes…..Ayacucho
1987 | Découvrir la subversion. Hommage à Edmond Jabès
1987 | Post-prae-ludium n. 1 per Donau

questo il codice per farla in markdown:

```
Data | Titolo | Ensemble | Ensemble | Live Electronics | Live Electronics | Live Electronics 
-----|-------|-----------|-----------|-----------------|-----------------|-----------------
1979 | Con Luigi Dallapiccola | Percussioni |  - | Ring Modulators | Oscillators
1981 | Das atmende Klarsein | Flauto | Coro | Halafon | Delay | Harmonizer
1981 | Io, frammento dal Prometeo
1982 | Quando stanno morendo. Diario polacco n. 2
1983 | Guai ai gelidi mostri
1983 | Omaggio a György Kurtág
1984 | Prometeo. Tragedia dell’ascolto
1985 | A Pierre. Dell’azzurro silenzio, inquietum
1986 | Risonanze erranti. Liederzyklus a Massimo Cacciari
1987 | 1° Caminantes…..Ayacucho
1987 | Découvrir la subversion. Hommage à Edmond Jabès
1987 | Post-prae-ludium n. 1 per Donau
```

**Comment by grammaton** [comment]
@DavideTedesco grazie. l'idea è riempiendola e magari impaginandola in latex di vedere a colpo d'occhio organici e strumenti elettronici usati in quel decennio

**Comment by DavideTedesco** [comment]
tutto ciò dove lo vogliamo posizionare all'interno di s-e-a-m @grammaton ?? nelle librerie o nelle References?

**Comment by grammaton** [comment]
nelle reference, nella cartella latex di nono

**Comment by DavideTedesco** [comment]
[ecco una prima versione con dati da aggiunger in latex](https://github.com/s-e-a-m/References/blob/master/Nono-Luigi/latex/Nono%20Luigi%20-%20Live%20Electronics%20Overview.tex)

**Comment by grammaton** [comment]
bene
