### ISSUE TITLE
How do I install this into Faust?

### ISSUE THREAD

**Issue by DavidsonAudioMulti** [s-e-a-m/faust-libraries#14]
I I am a beginner to Faust and I am wondering how to install this seam lib in Faust, should I put them all in the shared library folder wih the other libs? When I try to add the functions from these libs it just says can't be found.

Any help on this would be appreciated thank you !!!

**Comment by grammaton** [comment]
Hi @DavidsonAudioMulti, it depends on how do you use Faust.
Using the *webide* you have to simply drag your custom libraries close to your DSP and invoke them like *stdfaust.lib*.

```
import("seam.lib");
process = ma.PI*2, sma.twopi;
```

the seam.lib call also ask for import("stdfaust.lib").

each library has three letters index (sma. => seam math… etc).

With *webide*, you can import and write code, but you can not compile with external libraries (or if there is a way I do not know it). Nevertheless, you can compile offline without issue by command line.  

Hope it can help.
I appreciate your interest, so ask freely again if you need. 
SEAM has also a small [slack channel](https://join.slack.com/t/seam-world/shared_invite/zt-ekrwtpo3-mXz~GczNSLTIatlJyd4GGg
) to discuss.

Ciao!
Giuseppe

**Comment by DavidsonAudioMulti** [comment]
Thank you very much grammaton!!

I have faust setup working similar to Mr Smith's classroom presentation video using just notepad++, FaustLive, and the powershell. With these I can change the code and faustLive will update it takes a second to compile then I can see changes after saving the file. I found that this worked to call the external libraries from the dsp file on PC pretty reliably. Then as you instructed add the prepending two or three letter index value to call the external in the code. I will keep trying different combinations of tools seems to be a ton of development utilities and helper apps for faust. 

```
import("stdfaust.lib");
import("C:\Program Files\Faust\share\faust\userlib\Test.lib");
```

Really fun platform I am having a blast thanks Giuseppe!!
